### ISSUE TITLE
Need to Switch File Source

### ISSUE THREAD

**Issue by starsurfer87** [starsurfer87/DSCI100-Group-Project#1]
From my understanding, our python notebook needs to run without any external file so I think we have to read the data from a link. Not sure how to do this at the moment since just using the website url does not work, so I'm just reading in the data from a file in the repository for now.

**Comment by karlie-tr** [comment]
uploaded the file onto Github so we could download with the url

**Comment by starsurfer87** [comment]
Not sure if the commit worked as intended. I think you might have commited the .ipynb checkpoint file instead of the notebook itself? There's no need to include the checkpoint files since GitHub already does version control. Also, I already have a copy of the data uploaded to GitHub if that makes a difference.

**Comment by karlie-tr** [comment]
Thanks for letting me know, I might have commit & push incorrectly the first time. I deleted the file within the repository so we could try to download and read the file directly from the link.
